# Pre-commit hooks for code quality
# Install with: pre-commit install
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-toml
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: mixed-line-ending

  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
        language_version: python3
        args: [--config=pyproject.toml]

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: [--settings-path=pyproject.toml]

  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        additional_dependencies: [flake8-docstrings]

  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.9.0.2
    hooks:
      - id: shellcheck
        args: [-x, -S, warning]
        files: \.(sh|bash)$

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.991
    hooks:
      - id: mypy
        additional_dependencies: [types-requests, types-python-dateutil]
        exclude: ^(archive/|venv/|\.venv/)

  - repo: local
    hooks:
      - id: no-large-files
        name: Check for large files
        entry: bash -c 'find . -type f -size +1M -not -path "./.git/*" -not -path "./archive/*" -not -path "./venv/*" -not -path "./.venv/*" | head -1 | grep . && exit 1 || exit 0'
        language: system
        pass_filenames: false

      - id: no-debug-imports
        name: Check for debug imports
        entry: bash -c 'grep -r "import pdb\|import ipdb\|breakpoint()" --include="*.py" src/ scripts/ tools/ 2>/dev/null && exit 1 || exit 0'
        language: system
        pass_filenames: false
