---
- name: Configure Orlando Punx Infrastructure
  hosts: all
  become: yes
  vars_files:
    - ../group_vars/vault.yml
  roles:
    - common
    - docker
    - portainer
    - postgresql
    - nginx
    - ssl
    - cloudflare
    - ghost
    - gancio
    
  tasks:
    - name: Display infrastructure summary
      debug:
        msg: |
          🎸 Orlando Punx Infrastructure Deployed!
          
          📡 **Cloudflare Tunnel Services**:
          {% for instance_name, config in ghost_instances.items() %}
          - {{ config.domain }}: {{ config.url }} → localhost:{{ config.port }}
          {% endfor %}
          
          🖥️  **Management Interfaces**:
          - Portainer: https://{{ ansible_default_ipv4.address }}:9443
          - Ghost Admin Panels: [domain]/ghost/
          
          🔄 **Internal Ports** (tunnel access only):
          {% for instance_name, config in ghost_instances.items() %}
          - {{ config.port }}: {{ config.domain }}
          {% endfor %}
        
- name: Configure Web Services
  hosts: webservers
  become: yes
  vars_files:
    - ../group_vars/vault.yml
  tasks:
    - name: Restart nginx after configuration changes
      service:
        name: nginx
        state: restarted
        enabled: yes
      when: nginx_config_changed | default(false)
      
- name: Configure Ghost Services  
  hosts: ghostservers
  become: yes
  vars_files:
    - ../group_vars/vault.yml
  tasks:
    - name: Verify all Ghost instances are accessible
      uri:
        url: "http://localhost:{{ item.value.port }}"
        method: GET
        status_code: 200
      loop: "{{ ghost_instances | dict2items }}"
      ignore_errors: yes
      register: ghost_health_checks
      
    - name: Display Ghost instance status
      debug:
        msg: |
          Ghost Health Check Results:
          {% for result in ghost_health_checks.results %}
          - Port {{ result.item.value.port }} ({{ result.item.value.domain }}): {{ 'OK' if result.status == 200 else 'FAILED' }}
          {% endfor %}
